algoritmo "Calculoidade"

var
 ano, nasc, idade : inteiro
inicio
      escreva("Em que ano estamos?: ")
      leia(ano)
      escreva("Em que ano você nasceu?: ")
      leia(nasc)
      idade <- ano - nasc
      escreval ("Em ", ano, " voce tera ", idade, " anos.")
      Se (idade >= 21) entao
      escreval (" E voce ja tera atinjido a maioridade")
      fimse
      
      
fimalgoritmo
